# Site settings
title: Hiking metal punx forever
email: hikingmetalpunxforever@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about hiking, cycling, MYOG/DIY and whatever
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pikariop.github.io" # the base hostname & protocol for your site
github_username:  pikariop

# Build settings
markdown: kramdown
